#!/bin/sh -e

/opt/bin/ph15_email.py -t -d ou=user,ou=ph08,o=BMUKK -d ou=user,ou=ph15,o=BMUKK
/opt/bin/ldaptest.py --base-dn2 o=BMUKK -2 iter | \
    diff /opt/bin/testdata/ldapII.txt -
/opt/bin/testdriver.py -A 4731 -A 4732 deluids
/opt/bin/etl.py -c postgres -i 00000000000000000000000000000000 -t \
    -d ou=user,ou=ph08,o=BMUKK initial_load
/opt/bin/ldaptest.py --base-dn2 o=BMUKK -2 iter | \
    diff /opt/bin/testdata/ldap00.txt -
for test in 01 02 03 04 05 06 07 08 ; do
    echo $test
    /opt/bin/set_etd_done.py -U 4715
    /opt/bin/testdriver.py -A $test update
    /opt/bin/testdriver.py wait_for_sync
    if [ $test = 07 ] ; then
        sleep 3
    fi
    ( /opt/bin/ldaptest.py -2 iter | diff /opt/bin/testdata/ldap$test.txt - ) \
        || break
    /opt/bin/set_etd_done.py
done || exit 1
opt/bin/ldaptest.py --base-dn2 ou=user,ou=ph15,o=BMUKK -2 iter | \
    diff /opt/bin/testdata/ldapI15.txt -
